document.write('<!DOCTYPE html>');
document.write('<html lang="en">');
document.write('    <head>');
document.write('        <meta charset="utf-8">');
document.write('        <meta content="width=device-width, initial-scale=1.0" name="viewport">');
document.write('        <title>Ketan Sharma</title>');
document.write('        <link rel="stylesheet" href="assets/vender/portfolio-img/fancybox.css">');
document.write('        <link rel="stylesheet" href="assets/css/style.css">');
document.write('        <link rel="shortcut icon" href="assets/img/logo.png" type="image/x-icon">');
document.write('    </head>');
document.write('    <body>');
document.write('        <header class="header">');
document.write('            <i class="menu"></i>');
document.write('            <nav class="navbar">');
document.write('                <ul class="nav">');
document.write('                    <li class="active"><i class="nav-icon"></i><a');
document.write('                            href="#home" class="scroll-link">Home</a></li>');
document.write('                    <li><i class="nav-icon"></i><a href="#about"');
document.write('                            class="scroll-link">About</a></li>');
document.write('                    <li><i class="nav-icon"></i><a');
document.write('                            href="#resume" class="scroll-link">Resume</a></li>');
document.write('                    <li><i class="nav-icon"></i><a');
document.write('                            href="#portfolio"');
document.write('                            class="scroll-link">Portfolio</a></li>');
document.write('                    <li><i class="nav-icon"></i><a');
document.write('                            href="#services"');
document.write('                            class="scroll-link">Services</a></li>');
document.write('                    <li><i class="nav-icon"></i><a');
document.write('                            href="#contact" class="scroll-link">Contact</a></li>');
document.write('                </ul>');
document.write('            </nav>');
document.write('        </header>');
document.write('        <section class="home" id="home">');
document.write('            <h1>Ketan Sharma</h1>');
document.write('            <p>I\'m <span class="typed"');
document.write('                    data-typed-items="Student, Developer, Freelancer, Entrepreneur"></span></p>');
document.write('            <div class="sociallinks">');
document.write('                <ul>');
document.write('                    <li><a');
document.write('                            href="https://www.instagram.com/ketansharma911/"></a></li>');
document.write('                    <li><a');
document.write('                            href="https://www.linkedin.com/in/ketan-sharma-b1b0a5288/"></a></li>');
document.write('                    <li><a href="https://github.com/KetanSharma91"></a></li>');
document.write('                    <li><a href="https://x.com/KetanSharm37993"></a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </section>');
document.write('        <section class="about" id="about">');
document.write('            <h3>About Me</h3>');
document.write('            <p>I\'m a second-year BCA student specializing');
document.write('                in Data Science at Acharya Institute of Technology,');
document.write('                Bangalore. I have a keen interest in leveraging data to');
document.write('                solve real-world problems and an passionate about web');
document.write('                development and app development.</p>');
document.write('            <div class="content">');
document.write('                <div class="about-img"><img src="assets/img/profile-img.jpg"');
document.write('                        alt="profileimage"></div>');
document.write('                <div class="about-text">');
document.write('                    <h4>UI/UX Designer & Web Developer.</h4>');
document.write('                    <div class="text">');
document.write('                        <ul class="agecity"><li><span>Age</span> : 19 </li>');
document.write('                            <li><span>City</span> : Bengaluru </li>');
document.write('                        </ul>');
document.write('                        <ul>');
document.write('                            <li><span>Email</span> : ketbusiness12@gmail.com');
document.write('                            </li>');
document.write('                            <li><span>Education</span> : Bachelor of Computer');
document.write('                                Applications');
document.write('                                (Specialization in Data Science)');
document.write('                            </li>');
document.write('                            <li><span>Hobbies</span> : Coding, Exploring New');
document.write('                                Technologies,');
document.write('                                Designing Interfaces </li>');
document.write('                            <li><span>Skills</span> : Web Development, App');
document.write('                                Development, Data Management, UI/UX Design</li>');
document.write('                        </ul>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </section>');
document.write('        <section id="skills" class="skills">');
document.write('            <h3>Prgramming Languages</h3>');
document.write('            <p>');
document.write('                I have developed strong skills in various programming languages');
document.write('                and technologies crucial for web development.');
document.write('            </p>');
document.write('            <div class="skillset">');
document.write('                <div class="skill1">');
document.write('                    <div class="skill">');
document.write('                        <p>HTML</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 100%;">100%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>CSS</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 80%;">80%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>JavaScript</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 85%;">85%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <div class="skill">');
document.write('                        <p>PHP</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 40%;">40%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="skill2">');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>WordPress / Wix</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 60%;">60%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>Kotlin</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 25%;">25%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>Python</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 20%;">20%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('');
document.write('                    <div class="skill">');
document.write('                        <p>Java</p>');
document.write('                        <div class="progress-bar">');
document.write('                            <div class="progress"');
document.write('                                style="--target-width: 70%;">70%</div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </section>');
document.write('        <section id="resume" class="resume">');
document.write('            <h3>Resume</h3>');
document.write('            <div class="sets">');
document.write('                <div class="set1">');
document.write('                    <div class="profile">');
document.write('                        <h2>PROFILE</h2>');
document.write('                        <p>Second-year BCA student specializing in Data Science');
document.write('                            with a strong foundation in web development');
document.write('                            and');
document.write('                            a');
document.write('                            passion for app development. Seeking to leverage my');
document.write('                            skills and knowledge in a challenging');
document.write('                            internship.');
document.write('                        </p>');
document.write('                    </div>');
document.write('                    <div class="resumeskills">');
document.write('                        <h2>SKILLS</h2>');
document.write('                        <h4>Programming Languages: </h4>');
document.write('                        <ul>');
document.write('                            <li>Python,</li>');
document.write('                            <li>JavaScript,</li>');
document.write('                            <li>HTML/CSS</li>');
document.write('                        </ul>');
document.write('                        <h4>Tools and Technologies: </h4>');
document.write('                        <ul>');
document.write('                            <li>SQL,</li>');
document.write('                            <li>Node.js</li>');
document.write('                        </ul>');
document.write('                        <h4>Soft Skills: </h4>');
document.write('                        <ul>');
document.write('                            <li>Teamwork,</li>');
document.write('                            <li>Problem-solving,</li>');
document.write('                            <li>Communication</li>');
document.write('                        </ul>');
document.write('                    </div>');
document.write('                    <div class="lang">');
document.write('                        <h2>LANGUAGES</h2>');
document.write('                        <p>English: Intermediate <br>Hindi: Intermediate');
document.write('                            <br>Kannada: Intermediate </p>');
document.write('                    </div>');
document.write('                </div>');
document.write('                <div class="set2">');
document.write('                    <div class="edu">');
document.write('                        <h2>EDUCATION</h2>');
document.write('                        <h4>ACHARYA INSTITUTE OF TECHNOLOGY</h4>');
document.write('                        <p>2023-present</p>');
document.write('                        <i>Bachelor of Computer Applications, in progress.</i>');
document.write('');
document.write('                        <h4>ST.CLARET PU COLLEGE</h4>');
document.write('                        <p>2021-2023</p>');
document.write('                        <i>High School</i>');
document.write('');
document.write('                        <h4>STANDARD PUBLIC SCHOOL</h4>');
document.write('                        <p>2010-2021</p>');
document.write('                        <i>Middle And High School</i>');
document.write('                    </div>');
document.write('                    <div class="course">');
document.write('                        <h2>CERTIFICATIONS AND COURSES:</h2>');
document.write('                        <h4>RedHat Course</h4>');
document.write('                        <p>- Introduction to OpenShift Applications (DO101).</p>');
document.write('');
document.write('                        <h4>Coursera </h4>');
document.write('                        <p>');
document.write('                            - Systems and Application security <br>');
document.write('                            - Cryptography <br>');
document.write('                            - Networks and Communications security <br>');
document.write('                            - Access Controls');
document.write('                        </p>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <p class="downresume">download resume <a href="assets/Resume.pdf"');
document.write('                    download="Resume.pdf">here</a>');
document.write('            </p>');
document.write('        </section>');
document.write('        <section id="portfolio" class="portfolio">');
document.write('            <h3>Portfolio</h3>');
document.write('            <p>');
document.write('                Explore my portfolio to see a variety of projects I\'ve worked');
document.write('                on, including web applications, mobile apps, and UI/UX designs.');
document.write('                Each project showcases my skills and creativity in bringing');
document.write('                digital ideas to life.');
document.write('            </p>');
document.write('            <div class="row">');
document.write('                <ul class="row-content">');
document.write('                    <li><a data-filter="all" class="on">All</a></li>');
document.write('                    <li><a data-filter="web">Web</a></li>');
document.write('                    <li><a data-filter="app">App</a></li>');
document.write('                    <li><a data-filter="uiux">UI/UX</a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <div class="portfolio-sets">');
document.write('                <div class="portfolioset web">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-1.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>Web1</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-1.jpg"></i>');
document.write('                            <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset uiux">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-10.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>UI/UX3</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-10.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset web">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-2.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>Web2</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-2.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset app">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-7.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>App1</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-7.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset web">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-3.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>Web2</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-3.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset app">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-6.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>App1</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-6.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset web">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-4.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>Web2</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-4.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset uiux">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-9.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>UI/UX1</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-9.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset web">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-5.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>Web2</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-5.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('                <div class="portfolioset uiux">');
document.write('                    <div class="portimg"><img');
document.write('                            src="assets/img/portfolio/portfolio-8.jpg"');
document.write('                            alt></div>');
document.write('                    <div class="porttext">');
document.write('                        <p>UI/UX1</p>');
document.write('                        <div class="portlink"><i class="size"');
document.write('                                data-fancybox="gallery"');
document.write('                                data-src="assets/img/portfolio/portfolio-8.jpg"></i>');
document.write('                                <a href="https://insettprojects.rf.gd/projects.html"><i class="link"></i></a></div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('            </div>');
document.write('            <p class="projectslink">For more projects <a href="https://insettprojects.rf.gd">click');
document.write('                    here</a></p>');
document.write('        </section>');
document.write('        <section class="services" id="services">');
document.write('            <h3>Services</h3>');
document.write('            <p>What I can do for you</p>');
document.write('            <div class="service-container">');
document.write('                <div class="service">');
document.write('                    <div class="service-img"><img');
document.write('                            src="assets/img/service/service-1.jpg"');
document.write('                            alt="Web Development"></div>');
document.write('                    <h2>Web Development</h2>');
document.write('                    <p>Design and develop modern, responsive websites optimized');
document.write('                        for performance.</p>');
document.write('                </div>');
document.write('');
document.write('                <div class="service">');
document.write('                    <div class="service-img"><img');
document.write('                            src="assets/img/service/service-2.jpg"');
document.write('                            alt="App Development"></div>');
document.write('                    <h2>App Development</h2>');
document.write('                    <p>Build seamless mobile applications for Android and iOS');
document.write('                        platforms.</p>');
document.write('                </div>');
document.write('');
document.write('                <div class="service">');
document.write('                    <div class="service-img"><img');
document.write('                            src="assets/img/service/service-3.jpg"');
document.write('                            alt="Logo Design"></div>');
document.write('                    <h2>Logo Design</h2>');
document.write('                    <p>Create impactful logos that represent your brand');
document.write('                        identity.</p>');
document.write('                </div>');
document.write('');
document.write('                <div class="service">');
document.write('                    <div class="service-img"><img');
document.write('                            src="assets/img/service/service-4.jpg"');
document.write('                            alt="UI/UX"></div>');
document.write('                    <h2>UI/UX Design</h2>');
document.write('                    <p>Design intuitive and visually appealing user');
document.write('                        interfaces.</p>');
document.write('                </div>');
document.write('            </div>');
document.write('        </section>');
document.write('        <section id="contact" class="contact">');
document.write('            <h3>Contact</h3>');
document.write('            <div class="contact-content">');
document.write('                <div class="contact-left">');
document.write('                    <div class="contact-things">');
document.write('                        <i class="address-icon"></i>');
document.write('                        <div class="contact-text"><h4>Address :</h4>');
document.write('                            <p>Nagasandra Post ,Bangalore ,KA 560073</p>');
document.write('                        </div>');
document.write('');
document.write('                    </div>');
document.write('                    <div class="contact-things">');
document.write('                        <i class="email-icon"></i>');
document.write('                        <div class="contact-text"><h4>Email :</h4>');
document.write('                            <p>ketansharma.ks.911@gmail.com</p>');
document.write('                        </div>');
document.write('');
document.write('                    </div>');
document.write('                    <div class="contact-things">');
document.write('                        <i class="call-icon"></i>');
document.write('                        <div class="contact-text"><h4>Call :</h4>');
document.write('                            <p>+91 91132 83433</p>');
document.write('                        </div>');
document.write('');
document.write('                    </div>');
document.write('                </div>');
document.write('                <form action="assets/php/sendmail.php" method="post"');
document.write('                    id="contactForm">');
document.write('                    <div class="formtext">');
document.write('                        <input type="text" id="name" name="name"');
document.write('                            placeholder="Your Name" required />');
document.write('                        <input type="email" name="email" id="email"');
document.write('                            placeholder="Your Email" required />');
document.write('                    </div>');
document.write('                    <input type="text" name="subject" id="subject"');
document.write('                        placeholder="Subject" required />');
document.write('                    <textarea name="message" id="textarea"');
document.write('                        placeholder="Message" rows="3" required></textarea>');
document.write('                    <button type="submit" name="submitbtn">Submit</button>');
document.write('                    ');
document.write('                </form>');
document.write('            </div>');
document.write('        </section>');
document.write('        <footer>');
document.write('            <h1>KETAN SHARMA</h1>');
document.write('            <p>I\'m a web developer and designer specializing in building modern,');
document.write('                responsive websites and applications. Let\'s connect and create');
document.write('                something amazing together!</p>');
document.write('            <div class="sociallinks">');
document.write('                <ul>');
document.write('                    <li><a');
document.write('                            href="https://www.instagram.com/ketansharma911/"></a></li>');
document.write('                    <li><a');
document.write('                            href="https://www.linkedin.com/in/ketan-sharma-b1b0a5288/"></a></li>');
document.write('                    <li><a href="https://github.com/KetanSharma91"></a></li>');
document.write('                    <li><a href="https://x.com/KetanSharm37993"></a></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('            <p>© Copyright KetanSharma. All Rights Reserved</p>');
document.write('        </footer>');
document.write('        <script src="assets/vender/js/sweetalert2@11.js"></script>');
document.write('        <script src="assets/php/sweetform.js"></script>');
document.write('        <script src="assets/vender/portfolio-img/fancybox.umd.js"></script>');
document.write('        <script src="assets/vender/js/imagesloaded.pkgd.min.js"></script>');
document.write('        <script src="assets/vender/js/masonry.pkgd.min.js"></script>');
document.write('        <script src="assets/vender/js/typed.umd.js"></script>');
document.write('        <script src="assets/js/main.js"></script>');
document.write('    </body>');
document.write('</html>');

